name: Release Stable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: release-stable
  cancel-in-progress: true

jobs:
  release-stable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      NPM_CONFIG_PROVENANCE: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Build packages
        run: bun run build

      - name: Extract version from tag
        id: version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Publish to npm (stable)
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          
          # Publish docsfly
          cd packages/docsfly
          npm publish --tag latest
          cd ../..
          
          # Publish create-docsfly-app
          cd packages/create-docsfly-app
          npm publish --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Changes in this release

            See [CHANGELOG.md](./CHANGELOG.md) for details.
            
            ## Published packages
            
            - `docsfly@${{ steps.version.outputs.version }}`
            - `create-docsfly-app@${{ steps.version.outputs.version }}`
          draft: false
          prerelease: false