name: Release Beta

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

concurrency:
  group: release-beta
  cancel-in-progress: true

jobs:
  release-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NPM_CONFIG_PROVENANCE: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Build packages
        run: bun run build

      - name: Bump version to beta
        run: |
          # Get current timestamp for beta version
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          
          # Bump docsfly package
          cd packages/docsfly
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          BETA_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"
          bun version $BETA_VERSION --no-git-tag-version
          cd ../..
          
          # Bump create-docsfly-app package
          cd packages/create-docsfly-app
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          BETA_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"
          bun version $BETA_VERSION --no-git-tag-version
          cd ../..

      - name: Publish to npm (beta)
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          
          # Publish docsfly
          cd packages/docsfly
          npm publish --tag beta
          cd ../..
          
          # Publish create-docsfly-app
          cd packages/create-docsfly-app
          npm publish --tag beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}